import {
  BadgeCheck,
  Bot,
  CircleCheckBig,
  ClipboardList,
  FileCheck2,
  Hourglass,
  Landmark,
  Lock,
  MessageSquareText,
  Phone,
  PhoneOff,
  Search,
  Send,
  UserPlus,
  type LucideIcon,
} from "lucide-react";
import type { EventKind } from "@token-origins/schema";

export const EVENT_ICONS: Record<EventKind, LucideIcon> = {
  agent_registered: BadgeCheck,
  registry_search: Search,
  job_started: UserPlus,
  funds_locked: Lock,
  brief_parsed: ClipboardList,
  dialing: Phone,
  transcript_turn: MessageSquareText,
  on_hold: Hourglass,
  call_ended: PhoneOff,
  outcome_ready: CircleCheckBig,
  result_submitted: FileCheck2,
  result_delivered: Send,
  hirer_resumed: Bot,
  payment_collected: Landmark,
};
